<?php
/**
 * Payment Processing Script
 * Handles membership payments and renewals
 * Updates member expiry dates automatically
 */

require_once 'db_connect.php';

class PaymentProcessor {
    
    /**
     * Process membership payment
     * 
     * @param array $paymentData Payment information
     * @return array Result with success status and message
     */
    public static function processMembershipPayment(array $paymentData): array {
        try {
            // Validate required fields
            $required = ['member_id', 'type_id', 'amount', 'payment_method', 'processed_by'];
            foreach ($required as $field) {
                if (!isset($paymentData[$field]) || empty($paymentData[$field])) {
                    return [
                        'success' => false,
                        'message' => "Missing required field: $field"
                    ];
                }
            }

            // Start transaction
            Database::beginTransaction();

            // Get membership type details
            $membershipType = Database::querySingle(
                "SELECT * FROM membership_types WHERE type_id = ? AND is_active = 1",
                [$paymentData['type_id']]
            );

            if (!$membershipType) {
                Database::rollback();
                return [
                    'success' => false,
                    'message' => 'Invalid membership type selected'
                ];
            }

            // Get member details
            $member = Database::querySingle(
                "SELECT * FROM members WHERE member_id = ?",
                [$paymentData['member_id']]
            );

            if (!$member) {
                Database::rollback();
                return [
                    'success' => false,
                    'message' => 'Member not found'
                ];
            }

            // Calculate membership dates
            $startDate = $paymentData['start_date'] ?? date('Y-m-d');
            
            // Get current active membership to determine if renewal or new
            $currentMembership = Database::querySingle(
                "SELECT * FROM memberships 
                 WHERE member_id = ? AND status = 'Active' 
                 ORDER BY end_date DESC LIMIT 1",
                [$paymentData['member_id']]
            );

            // If renewing, start from current end date if it's in the future
            if ($currentMembership && $currentMembership['end_date'] > date('Y-m-d')) {
                $startDate = $currentMembership['end_date'];
            }

            // Calculate end date based on membership duration
            $endDate = date('Y-m-d', strtotime($startDate . ' + ' . $membershipType['duration_months'] . ' months'));

            // Expire old memberships
            Database::execute(
                "UPDATE memberships SET status = 'Expired' 
                 WHERE member_id = ? AND status = 'Active'",
                [$paymentData['member_id']]
            );

            // Create new membership record
            $membershipQuery = "INSERT INTO memberships 
                (member_id, type_id, start_date, end_date, amount_paid, status, enrolled_by, notes) 
                VALUES (?, ?, ?, ?, ?, 'Active', ?, ?)";
            
            Database::execute($membershipQuery, [
                $paymentData['member_id'],
                $paymentData['type_id'],
                $startDate,
                $endDate,
                $paymentData['amount'],
                $paymentData['processed_by'],
                $paymentData['notes'] ?? null
            ]);

            $membershipId = Database::lastInsertId();

            // Get payment type ID for membership
            $paymentType = Database::querySingle(
                "SELECT payment_type_id FROM payment_types WHERE type_name = 'Membership Fee'"
            );

            // Create payment record
            $paymentQuery = "INSERT INTO payments 
                (member_id, membership_id, payment_type_id, amount, payment_method, 
                 payment_date, processed_by, transaction_id, notes) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            Database::execute($paymentQuery, [
                $paymentData['member_id'],
                $membershipId,
                $paymentType['payment_type_id'],
                $paymentData['amount'],
                $paymentData['payment_method'],
                date('Y-m-d'),
                $paymentData['processed_by'],
                $paymentData['transaction_id'] ?? null,
                $paymentData['notes'] ?? 'Membership payment'
            ]);

            $paymentId = Database::lastInsertId();

            // Get receipt number (auto-generated by trigger)
            $payment = Database::querySingle(
                "SELECT receipt_number FROM payments WHERE payment_id = ?",
                [$paymentId]
            );

            // Update member status to Active
            Database::execute(
                "UPDATE members SET status = 'Active' WHERE member_id = ?",
                [$paymentData['member_id']]
            );

            // Log activity
            log_activity(
                $paymentData['processed_by'],
                'PAYMENT_PROCESSED',
                'payments',
                (int)$paymentId,
                "Membership payment processed for member ID: {$paymentData['member_id']}"
            );

            // Commit transaction
            Database::commit();

            return [
                'success' => true,
                'message' => 'Payment processed successfully',
                'data' => [
                    'membership_id' => $membershipId,
                    'payment_id' => $paymentId,
                    'receipt_number' => $payment['receipt_number'],
                    'start_date' => $startDate,
                    'end_date' => $endDate,
                    'amount' => $paymentData['amount'],
                    'membership_type' => $membershipType['type_name']
                ]
            ];

        } catch (Exception $e) {
            Database::rollback();
            error_log("Payment processing failed: " . $e->getMessage());
            return [
                'success' => false,
                'message' => 'Payment processing failed. Please try again.'
            ];
        }
    }

    /**
     * Process personal training payment
     * 
     * @param array $paymentData Payment information
     * @return array Result with success status and message
     */
    public static function processPersonalTrainingPayment(array $paymentData): array {
        try {
            // Validate required fields
            $required = ['member_id', 'trainer_id', 'amount', 'payment_method', 'processed_by'];
            foreach ($required as $field) {
                if (!isset($paymentData[$field]) || empty($paymentData[$field])) {
                    return [
                        'success' => false,
                        'message' => "Missing required field: $field"
                    ];
                }
            }

            Database::beginTransaction();

            // Get trainer commission rate
            $trainer = Database::querySingle(
                "SELECT commission_rate FROM staff WHERE staff_id = ?",
                [$paymentData['trainer_id']]
            );

            if (!$trainer) {
                Database::rollback();
                return [
                    'success' => false,
                    'message' => 'Trainer not found'
                ];
            }

            // Get payment type ID for personal training
            $paymentType = Database::querySingle(
                "SELECT payment_type_id FROM payment_types WHERE type_name = 'Personal Training'"
            );

            // Commission will be calculated by trigger
            $paymentQuery = "INSERT INTO payments 
                (member_id, payment_type_id, amount, payment_method, payment_date, 
                 processed_by, trainer_id, transaction_id, notes) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            Database::execute($paymentQuery, [
                $paymentData['member_id'],
                $paymentType['payment_type_id'],
                $paymentData['amount'],
                $paymentData['payment_method'],
                date('Y-m-d'),
                $paymentData['processed_by'],
                $paymentData['trainer_id'],
                $paymentData['transaction_id'] ?? null,
                $paymentData['notes'] ?? 'Personal training session payment'
            ]);

            $paymentId = Database::lastInsertId();

            // Get payment details including commission
            $payment = Database::querySingle(
                "SELECT receipt_number, commission_amount FROM payments WHERE payment_id = ?",
                [$paymentId]
            );

            // If session details provided, create PT session record
            if (isset($paymentData['session_date']) && isset($paymentData['session_time'])) {
                $sessionQuery = "INSERT INTO pt_sessions 
                    (member_id, trainer_id, session_date, session_time, fee, payment_id, status) 
                    VALUES (?, ?, ?, ?, ?, ?, 'Completed')";
                
                Database::execute($sessionQuery, [
                    $paymentData['member_id'],
                    $paymentData['trainer_id'],
                    $paymentData['session_date'],
                    $paymentData['session_time'],
                    $paymentData['amount'],
                    $paymentId
                ]);
            }

            log_activity(
                $paymentData['processed_by'],
                'PT_PAYMENT_PROCESSED',
                'payments',
                (int)$paymentId,
                "Personal training payment processed for member ID: {$paymentData['member_id']}"
            );

            Database::commit();

            return [
                'success' => true,
                'message' => 'Personal training payment processed successfully',
                'data' => [
                    'payment_id' => $paymentId,
                    'receipt_number' => $payment['receipt_number'],
                    'amount' => $paymentData['amount'],
                    'commission' => $payment['commission_amount']
                ]
            ];

        } catch (Exception $e) {
            Database::rollback();
            error_log("PT payment processing failed: " . $e->getMessage());
            return [
                'success' => false,
                'message' => 'Payment processing failed. Please try again.'
            ];
        }
    }

    /**
     * Get payment receipt data
     * 
     * @param int $paymentId
     * @return array|false
     */
    public static function getPaymentReceipt(int $paymentId): array|false {
        $query = "SELECT 
            p.*,
            CONCAT(m.first_name, ' ', m.last_name) as member_name,
            m.member_code,
            m.phone as member_phone,
            m.email as member_email,
            pt.type_name as payment_type,
            CONCAT(s.first_name, ' ', s.last_name) as processed_by_name,
            mt.type_name as membership_type,
            ms.start_date as membership_start,
            ms.end_date as membership_end
        FROM payments p
        JOIN members m ON p.member_id = m.member_id
        JOIN payment_types pt ON p.payment_type_id = pt.payment_type_id
        LEFT JOIN staff s ON p.processed_by = s.staff_id
        LEFT JOIN memberships ms ON p.membership_id = ms.membership_id
        LEFT JOIN membership_types mt ON ms.type_id = mt.type_id
        WHERE p.payment_id = ?";

        return Database::querySingle($query, [$paymentId]);
    }

    /**
     * Get member payment history
     * 
     * @param int $memberId
     * @param int $limit
     * @return array
     */
    public static function getPaymentHistory(int $memberId, int $limit = 10): array {
        $query = "SELECT 
            p.payment_id,
            p.receipt_number,
            p.payment_date,
            p.amount,
            p.payment_method,
            pt.type_name as payment_type,
            CONCAT(s.first_name, ' ', s.last_name) as processed_by
        FROM payments p
        JOIN payment_types pt ON p.payment_type_id = pt.payment_type_id
        LEFT JOIN staff s ON p.processed_by = s.staff_id
        WHERE p.member_id = ?
        ORDER BY p.payment_date DESC
        LIMIT ?";

        return Database::query($query, [$memberId, $limit]) ?: [];
    }
}

// Handle AJAX requests
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    header('Content-Type: application/json');
    
    // Verify CSRF token
    if (!verify_csrf_token($_POST['csrf_token'] ?? '')) {
        echo json_encode(['success' => false, 'message' => 'Invalid security token']);
        exit;
    }

    $action = sanitize_input($_POST['action']);
    
    switch ($action) {
        case 'process_membership':
            $paymentData = [
                'member_id' => (int)$_POST['member_id'],
                'type_id' => (int)$_POST['type_id'],
                'amount' => (float)$_POST['amount'],
                'payment_method' => sanitize_input($_POST['payment_method']),
                'processed_by' => (int)$_SESSION['staff_id'],
                'transaction_id' => sanitize_input($_POST['transaction_id'] ?? null),
                'notes' => sanitize_input($_POST['notes'] ?? null),
                'start_date' => sanitize_input($_POST['start_date'] ?? null)
            ];
            
            $result = PaymentProcessor::processMembershipPayment($paymentData);
            echo json_encode($result);
            break;

        case 'process_pt_payment':
            $paymentData = [
                'member_id' => (int)$_POST['member_id'],
                'trainer_id' => (int)$_POST['trainer_id'],
                'amount' => (float)$_POST['amount'],
                'payment_method' => sanitize_input($_POST['payment_method']),
                'processed_by' => (int)$_SESSION['staff_id'],
                'transaction_id' => sanitize_input($_POST['transaction_id'] ?? null),
                'notes' => sanitize_input($_POST['notes'] ?? null),
                'session_date' => sanitize_input($_POST['session_date'] ?? null),
                'session_time' => sanitize_input($_POST['session_time'] ?? null)
            ];
            
            $result = PaymentProcessor::processPersonalTrainingPayment($paymentData);
            echo json_encode($result);
            break;

        case 'get_receipt':
            $paymentId = (int)$_POST['payment_id'];
            $receipt = PaymentProcessor::getPaymentReceipt($paymentId);
            
            if ($receipt) {
                echo json_encode(['success' => true, 'data' => $receipt]);
            } else {
                echo json_encode(['success' => false, 'message' => 'Receipt not found']);
            }
            break;

        case 'get_payment_history':
            $memberId = (int)$_POST['member_id'];
            $history = PaymentProcessor::getPaymentHistory($memberId);
            echo json_encode(['success' => true, 'data' => $history]);
            break;

        default:
            echo json_encode(['success' => false, 'message' => 'Invalid action']);
    }
    exit;
}
?>
